#!/bin/bash
#$ -S /bin/bash
#$ -cwd
#$ -M michelle.liu@berkeley.edu
#$ -m e
#$ -j y
#$ -N all_coarse_6.8
#$ -o log/$JOB_NAME.log
#$ -pe threaded 4

skip=0
total_time=200000 #4000000
meas_time=20000 #50000

######### 6.8 AA coarse-grained wall #########
suffix=coarse-6.8
num_particles=288
sep=6.8
oid=1

inp_file=../coarse_6.8/coarse_6.8.t160140-20fs.traj
dump_step=20
./bin/correlation -s $skip -t $total_time -m $meas_time -d $sep -e $suffix -w $num_particles -o $oid -r $dump_step $inp_file

inp_file=../coarse_6.8/coarse_6.8.t160140-0.5fs.traj
dump_step=0.5
./bin/hbonds -s $skip -t $total_time -m $meas_time -d $sep -e $suffix -w $num_particles -o $oid -r $dump_step -C -V $inp_file

inp_file=../coarse_6.8/coarse_6.8.m160140.out
dump_step=20
./bin/dipole -s $skip -t $total_time -m $meas_time -d $sep -e $suffix -w $num_particles -r $dump_step $inp_file
